### ISSUE TITLE
Game missing. New Super Luigi U

### ISSUE THREAD

**Issue by LeonardFiedrowicz** [LeonardFiedrowicz/galaxy-integration-cemu#1]

**Comment by Wibbbs** [comment]
I just ran into this issue. Just wondering if there has been any fix? This is the only game that hasnt shown up for me.

**Comment by HengiFettlich** [comment]
It would be helpful to have the meta.xml file of the game

**Comment by Wibbbs** [comment]
Pasted the XML here

[https://pastebin.com/GjBVVjRw](https://pastebin.com/GjBVVjRw)

**Comment by LeonardFiedrowicz** [comment]
I think this is because the game is listed as an Expansion on igdb.com which is the database they use.
The game is both a standalone expansion and an expansion/dlc so that isn't really wrong, so I'm not sure if one should try to change it in the database or if GOG takes standalone expansion.
