### ISSUE TITLE
Games with version numbers other than 0 get filtered out

### ISSUE THREAD

**Issue by HengiFettlich** [LeonardFiedrowicz/galaxy-integration-cemu#11]
There are Games that ship with a higher version number by default. https://github.com/LeonardFiedrowicz/galaxy-integration-cemu/blob/54aa0082c72be7f07c5dbbdb36c2cbacaa8b253f/plugin.py#L249-L250
These Games will be filtered out here. Could be related to #1 and #9

**Comment by LeonardFiedrowicz** [comment]
Yes, that is related to #9 but not #1. I didn't actually put that in a release but I guess I should fix that here as well.

**Comment by LeonardFiedrowicz** [comment]
I put that in the master branch now.

**Comment by LeonardFiedrowicz** [comment]
Also, any other idea how to differentiate between games an update? I haven't found any.

**Comment by HengiFettlich** [comment]
Cemu does it by comparing the title_version in the meta.xml files. The lowest title_version of each title_id is the base game

**Comment by LeonardFiedrowicz** [comment]
Hm, that should work. Thanks.
