### ISSUE TITLE
Time not updating

### ISSUE THREAD

**Issue by Anitaz05** [LeonardFiedrowicz/galaxy-integration-cemu#14]
I'm using the latest version but when i choose my games and cemu folder i still dont get the times on gog. Any idea why? Thanks

**Comment by LeonardFiedrowicz** [comment]
Hm...could you check if cemu updates the times correctly (stored in the settings.xml, playtime in seconds and date as a unix time stamp).

@HengiFettlich Any idea?

**Comment by Anitaz05** [comment]
I have this settings.xml file i guess the times are right, the Hyrule Warriors game is the only one that shows the time on gog.


![image](https://user-images.githubusercontent.com/46374260/71269640-bbe1a980-2347-11ea-8287-98593761e8d5.png)

**Comment by HengiFettlich** [comment]
That's pretty weird indeed. The BOTW Path is kind of wrong, it could be that the path is just wrong. 
Wind Waker HD won't update, because the time_played is 0

**Comment by Anitaz05** [comment]
Oh nice! I got rid of the past with the numbers in BOTW and it worked!! Thanks for the help and continue with this awesome work ! :)
