### ISSUE TITLE
Play button missin in context menu

### ISSUE THREAD

**Issue by Wibbbs** [LeonardFiedrowicz/galaxy-integration-cemu#15]
Games were integrated and are launching fine thanks so much. But I noticed that the contect menu when right clickgin on a game does not have the play button. When clicking where the Play button should be it works, but it just shows a white circle.

Same issue when hovering over a game.

Context Menu
![image](https://user-images.githubusercontent.com/24574428/71419922-3f4d1480-2640-11ea-8c68-61bfcd000072.png)

Hover over game
![image](https://user-images.githubusercontent.com/24574428/71419928-4bd16d00-2640-11ea-83fa-92e8eba54538.png)

**Comment by LeonardFiedrowicz** [comment]
That's an issue with GOG as far as I know.
Although kinda weird that it works for the gamecube plugin but not for the wii plugin (even though they are basically the same).
