### ISSUE TITLE
Game title is missplaced in the popUp

### ISSUE THREAD

**Issue by Acid-Crash** [LeonardFiedrowicz/galaxy-integration-cemu#19]
**Win 10x64 GOG Galaxy v2.0.12**
I have noticed that all the games from Cemu plugin have missplaced names in the popUp menu (the one shown when hovering over the card).
![изображение](https://user-images.githubusercontent.com/32600318/72687767-dc994c80-3b09-11ea-9392-f479e14e2772.png)
The name is missplaced, additionally each word is moved to a new line.
_Captain Toad: Treasure Tracker_ 
becomes
_Captain 
Toad: 
Treasure 
Tracker_

_Mario Kart 8_ 
becomes
_Mario 
Kart 
8_

The happens to every game.
Regular integrations work fine.

**Comment by LeonardFiedrowicz** [comment]
I'm not sure why that is honestly. It may be an issue with GOG but I don't really know. It doesn't happen with my other integration for some reason.

**Comment by Acid-Crash** [comment]
Hi here.
GOG 2.0 come through few updates and the issue unfortunately is still here.
Are there any updates on this?

**Comment by LeonardFiedrowicz** [comment]
I still don't know what causes it.

**Comment by Acid-Crash** [comment]
Hi,
After update of GOG Galaxy to 2.0.16 the issue is gone
