### ISSUE TITLE
Cemu appears offline

### ISSUE THREAD

**Issue by Winter-arrow** [LeonardFiedrowicz/galaxy-integration-cemu#21]
Cemu integration says it is "Offline" and will not populate. Tried this with a fresh install of Cemu and it didn't change,

**Comment by LeonardFiedrowicz** [comment]
Can you upload the log file located at
`C:\ProgramData\GOG.com\Galaxy\logs\plugin-nwiiu-[...].log`

**Comment by Winter-arrow** [comment]
[plugin-nwiiu-1023214b-fd5d-45fd-9671-c080e92b03bb.log](https://github.com/LeonardFiedrowicz/galaxy-integration-cemu/files/4542230/plugin-nwiiu-1023214b-fd5d-45fd-9671-c080e92b03bb.log)

**Comment by LeonardFiedrowicz** [comment]
There seems to be an issue finding the games (with search subfolders enabled). Can you try inserting the file paths without " ... "?

**Comment by Winter-arrow** [comment]
That fixed it! Thanks!
