### ISSUE TITLE
List DLC for games

### ISSUE THREAD

**Issue by LeonardFiedrowicz** [LeonardFiedrowicz/galaxy-integration-cemu#3]

**Comment by UncleGoogle** [comment]
Galaxy do not support DLCs yet, but probably will it in the future as it is present in the API

**Comment by LeonardFiedrowicz** [comment]
Ah, thank you. 

Also, have you tried the plugin and is it working so far? Want to get some feedback ^^

**Comment by NoShotz** [comment]
I've tried the plugin, and it is working great. Legitimately just searched github and found it last night an hour after the latest commit.
