### ISSUE TITLE
GOG Galaxy wont launch games

### ISSUE THREAD

**Issue by joshuadyson** [LeonardFiedrowicz/galaxy-integration-cemu#5]
i had set the path correctly for both my ROMS and my cemu folder. yet when i hit play in gog it just shows "please wait we are launching a Nintendo Wii U game" and dose nothing when it disappears.

**Comment by LeonardFiedrowicz** [comment]
Please upload the wiiu logs file at for example
`"C:\ProgramData\GOG.com\Galaxy\logs\plugin-nwiiu-1023214b-fd5d-45fd-9671-c080e92b03bb.log"`

I can't really tell you anything without that.

Emulator paths should look something like this (maybe i should specify that i mean the folder and not the cemu.exe...)
`E:\Emulator\Emulatoren\Nintendo Wii U - Cemu`

and ROM paths like this
`E:\Emulator\ROMs\Nintendo - Wii U`

**Comment by joshuadyson** [comment]
i had tried both the folder the cemu.exe is in, as well as specifying the .exe itself. i assumed it was the folder not the exe you wanted because that was the only way i got the play time's.


Uploaded it to google drive as im still new too github.
https://drive.google.com/file/d/1m8u2BUgOUt3d-6lvbFMzkwc8BME2H0P5/view?usp=sharing

**Comment by LeonardFiedrowicz** [comment]
Okay, will take a look at it.

Is the game, update and dlc all in the rom folder for breath of the wild? It seems like it finds the game three times.

And launching Cemu seems to fail because of missing permission. Are you launching cemu as an admin or have in in a folder that requires adming rights like C:\Program Files?

To upload files on github just drag them over the comment box ^^
I'm pretty new to github myself as well. This is my first public repository.

**Comment by joshuadyson** [comment]
i have cemu launching as admin yes, and its not in a folder like that. and yes i have all of the roms for BOTW in a single folder along with other roms like twilight princess and wind waker, could that be a problem?

**Comment by LeonardFiedrowicz** [comment]
You would need to grant the plugin admin permission if it's supposed to open something that requires admin permission it seems (or dont require admin permission to open cemu). Would need to look into if I can ask for admin permission if needed.

About the with the updates and such. I could check the version number of the game in the folder it only allow ones that are 0 (so base game, not the update) to filter them out.
Did BotW show up in the library 3 times by the way? Looks like it in the log. And did the playtime for BotW display correctly in GOG?

**Comment by joshuadyson** [comment]
the playtime displayed correctly, and it only displayed twice not 3 times, i assume one was the DLC being read and the other is the main game. how would i go about giving the plugin admin perms on my end?

**Comment by LeonardFiedrowicz** [comment]
Try the new release and tell me if there still are duplicates. It doesn't change anything about the admin thing though.

Maybe launch GOG as admin or set the python.py file to require admin rights?
Does cemu gain anything from requiring admin permission by the way?

I would try to check if I can ask for admin permission when launching cemu tomorrow.

**Comment by joshuadyson** [comment]
i beleave i had done it a while ago for performance reasons, i dont remember exactly why. disabling cemu running as admin fixed the problem though, so theres that. thanks for the help, if i notice any performance difference ill probably put cemu back to admin than give gog admin perms and the same for the python file. gonna test the new release for ya right now

**Comment by joshuadyson** [comment]
the release did remove the second BOTW. thanks man, however i did just notice Twilight Princess is missing now

**Comment by LeonardFiedrowicz** [comment]
Can you upload the meta.xml file in the meta folder from twilight princess?
It currently sorts games out if its a dlc or update. That would sort games out if you overwrite the base game with update files (which you shouldn't, cemu can handle that).
