### ISSUE TITLE
Time played only updates when starting launcher or (re)integrating platform

### ISSUE THREAD

**Issue by riku55** [LeonardFiedrowicz/galaxy-integration-cemu#6]
Integrating games and cemu worked like a charm, though to update to the correct play time right after playing, I need to restart Galaxy 2.0 or reconnect the integration. Having a method that updates play time after playing or every now and then would be nice I think :)

**Comment by LeonardFiedrowicz** [comment]
Yeah, its currently like that, since  gog only serms to call get_game_time once.
I could try to update that every 5min or so. Or do you think thats too long and every minute or every 10s would be better?

**Comment by riku55** [comment]
Hm, ideally I would say to adjust it to the timing other integrations use. Not sure what timing they use though. I'd say every minute is fine.

**Comment by LeonardFiedrowicz** [comment]
I just noticed another problem. Cemu doesn't track time when starting the games outside of cemu like I do here...

This might be more complicated than I though.

**Comment by Geroyuni** [comment]
Hi, just a heads up, I've reported it to them and [it's getting fixed on 1.15.18](http://cemu.info/patreon/changelog/cemu_1_15_18.txt)

**Comment by LeonardFiedrowicz** [comment]
Thank you ^^
