### ISSUE TITLE
Not pulling all games

### ISSUE THREAD

**Issue by Curotos** [LeonardFiedrowicz/galaxy-integration-cemu#7]
When I set up my folder for the roms, gog detected only super Mario bros u. I have two other games and I am confused on how I can get them to show up any help would be really appreciated!

**Comment by LeonardFiedrowicz** [comment]
Can you try if they show up in release 1.0?

And did you overwrite base game files with update files for those games that are missing?

**Comment by LeonardFiedrowicz** [comment]
I deleted the version with that filtered the updates now since it didn't really work the way I tried.
So all games should show up now.
